inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("album/new", views.album_new, name="album_new"),
    path("artist/new", views.artist_new, name="artist_new")
]

record_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('account/logout/', LogoutView.as_view(next_page='/inventory'), name='logout')
]

inventory/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=255)
    still_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    stock_level = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

inventory/forms.py
from django import forms

from .models import *

class AlbumForm(forms.ModelForm):

    artist = forms.ModelChoiceField(Artist.objects.all())

    class Meta:
        model = Album
        fields = ('title', 'year', 'stock_level', 'artist')


class ArtistForm(forms.ModelForm):

    class Meta:
        model = Artist
        fields = ('name',)

inventory/views.py
from inventory.forms import AlbumForm, ArtistForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from inventory.models import *
from .forms import AlbumForm, ArtistForm
# Create your views here.

def index(request):
    artists = Artist.objects.all()
    return render(request, "inventory/index.html", locals())

@login_required
def album_new(request):
    if request.method == "POST":
        form = AlbumForm(request.POST)
        if form.is_valid():
            album = form.save(commit=False)
            album.save()
            return redirect("index")
    else:
        form = AlbumForm()
        return render(request, "inventory/album_form.html", {'form': form})


@login_required
def artist_new(request):
    if request.method == "POST":
        form = ArtistForm(request.POST)
        if form.is_valid():
            artist = form.save(commit=False)
            artist.save()
            return redirect("index")
    else:
        form = ArtistForm()
        return render(request, "inventory/artist_form.html", {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Record Store</title>
</head>
<body>
    <div class="header">
		<div>
			<nav class="navbar navbar-expand-lg">
				<ul class="navbar-nav">
					<li class="nav"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
					{% if user.is_authenticated %}
					<li class="nav"><a class="navbar-brand" href="{% url 'album_new' %}" >Add Album</a></li> 
					<li class="nav"><a class="navbar-brand" href="{% url 'artist_new' %}" >Add Artist</a></li> 
					<p>Hello {{user.first_name}}! <small><a href="{% url 'logout' %}">Log Out</a></small></p>
					{% else %}
					<li><a href="{% url 'login' %}">Log In</a></li>

					{% endif %}
				</div>
			</ul>
		</nav>
	</div>
</div>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/inventory/album_form.html
{% extends "base.html" %}

{% block content %}
    <h2>New Album</h2>
    <form method="POST">
        {% csrf_token %}

        <div>
            {{form.as_p}}
        </div>
        <button type="submit">Save</button>

    </form>
{% endblock %}

templates/inventory/artist_form.html
{% extends "base.html" %}

{% block content %}
    <h2>New Artist</h2>
    <form method="POST">
        {% csrf_token %}

        <div>
            {{form.as_p}}
        </div>
        <button type="submit">Save</button>

    </form>
{% endblock %}

templates/inventory/index.html
{% extends "base.html" %}

{% block content %}

    {% for artist in artists %}
        <h2>{{artist.name}}</h2>
            <ul>
                {% for album in artist.album_set.all %}
                    <li>{{album.title}} - {{album.year}}</li>
                {% endfor %}
            </ul>
    {% endfor %}

{% endblock %}